version: '3.8'
services:
    listvehiclesapi:
        build:
            context: ./listvehiclesapi
            target: development
        volumes:
            - ./listvehiclesapi:/src
            - /src/node_modules
        command: npm run start:dev
        ports:
            - "8081:8000"
        environment: 
            NODE_ENV: development
            DEBUG: src:*
